The target variable you want to predict:
1-year account revenue growth ( in $)

How predicting that target variable could help with some kind of decision:
Resource and staffing 

The features you want to use to predict that target variable:
account descriptive data and product usage data

Goals and success metrics:
Linear regression: R squared/ MSE

Risks or limitations:
Only using a subset of customer - smallest accounts
Pulled two years worth of data, in an effort to have more data
if an account was active both years I split up the data into two rows( may only use the most recent year- if there appears to be isssue with having 2 rows per account)

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

project = pd.read_csv('../part1/Project_data.csv')
project.head()

,Obs_No,AR #,Obs Year,Year Live,DaysSinceLive,EE Year Count,ARR Year Growth,ARR Start,ARR_EndOfYear,BOut75K,...,Category_Account Health,RefNo_Cumulative,Conference Attendance,Training Hours,Training Students,Percent of Book,ACT Score,BI Score,Ave P_Score,Model
0,1,ABE1000,2017,2011,1823,217,4753.0,66054,70807.0,0.0,...,1,0,0,0.0,0,1.172813,103.600918,8.841379,118.166034,1
1,2,ABE1000,2018,2011,2188,218,5866.0,70807,76673.0,1.0,...,1,0,0,0.0,0,1.099129,103.108676,3.775498,73.553312,1
2,3,ABI1002,2018,2016,240,381,39173.0,73369,112542.0,1.0,...,1,0,0,0.0,0,2.492619,52.468248,1.425152,17.787642,1
3,4,ACC1004,2017,2010,2261,220,3192.0,31944,35136.0,0.0,...,1,0,0,36.0,4,1.714876,9.036163,15.128390,9.036163,1
4,5,ACC1004,2018,2010,2626,220,3504.0,35136,38640.0,0.0,...,1,0,0,36.0,4,1.559085,30.368201,15.128390,30.368201,1